---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovms
  labels:
    app: ovms
spec:
  selector:
    matchLabels:
       app: ovms
  replicas: 1
  template:
    metadata:
      labels:
        app: ovms
    spec:
      containers:
      - name: ovms-resnet
        image: intelaipg/openvino-model-server:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: "GOOGLE_APPLICATION_CREDENTIALS"
          value: /secret/gcp-creds.json
        command: ["/ie-serving-py/start_server.sh"]
        args: ["ie_serving", "model", "--model_path", "gs://models-repository", "--model_name", "icnet-camvid-ava-0001", "--port", "8080", "--batch_size", "auto"]
        volumeMounts:
        - name: gcpcreds
          mountPath: "/secret"
          readOnly: true
      volumes:
      - name: gcpcreds
        secret:
          secretName: gcpcreds