kind: Service
apiVersion: v1
metadata:
  name: openvino-model-server
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    role: model_server
  type: LoadBalancer
